# Generated by Django 5.1.1 on 2024-09-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('seeds', 'Seeds'), ('machines', 'Machinery'), ('fertilizer', 'Fertilizer')], max_length=20),
        ),
    ]
