# Generated by Django 5.1.1 on 2024-09-12 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_delete_category_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
