# Generated by Django 5.1.1 on 2024-09-12 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_otp_user_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
