# Generated by Django 5.1.1 on 2024-09-12 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
